/* Copyright 2016 Peter Goodman (peter@trailofbits.com), all rights reserved. */

#ifndef VMILL_SNAPSHOT_SNAPSHOT_H_
#define VMILL_SNAPSHOT_SNAPSHOT_H_

#include <memory>

// Auto-generated by cmake/protobuf inside the build directory.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wshorten-64-to-32"
#include <Snapshot.pb.h>
#pragma clang diagnostic pop

using ProgramSnapshotPtr = std::unique_ptr<grr::snapshot::Program>;

#endif  // VMILL_SNAPSHOT_SNAPSHOT_H_
