/*
 * Copyright (c) 2017 Trail of Bits, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef VMILL_CONTEXT_SNAPSHOT_H_
#define VMILL_CONTEXT_SNAPSHOT_H_

#include <memory>
#include <string>

// Auto-generated by cmake/protobuf inside the build directory.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wshorten-64-to-32"
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wsign-compare"
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#include <Snapshot.pb.h>
#pragma clang diagnostic pop

namespace vmill {

class ProgramSnapshotPtr : public std::unique_ptr<snapshot::Program> {
 public:
  using unique_ptr::unique_ptr;
};

// Load in the snapshot from the workspace.
ProgramSnapshotPtr LoadSnapshotFromFile(const std::string &snapshot_path);

}  // namespace vmill

#endif  // VMILL_CONTEXT_SNAPSHOT_H_
